project_id = "fmivcwetejazikuyfmqn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes_enabled = false

[functions.moto-payment]
verify_jwt = false

[functions.create-test-order]
verify_jwt = false