// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmivcwetejazikuyfmqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaXZjd2V0ZWphemlrdXlmbXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjE5MTMsImV4cCI6MjA1NzAzNzkxM30.D4Z6QZfg4mXBuserzekG-prqcSsA81iDvudmFChlYYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);